steps:
  - command: |
      echo "--- Creating symbolic link to job directory :file_folder:" && \
      sleep 5 && ln -s "$(pwd)" /data/job && cd /data/job && \
      echo "+++ Building :hammer:" && \
      echo 1 | ./eosio_build.sh && \
      echo "--- Compressing build directory :compression:" && \
      tar -pczf build.tar.gz build/
    label: ":darwin: High Sierra Build"
    agents:
      - "role=macos-builder"
    artifact_paths: "build.tar.gz"
    timeout: 60

  - command: |
      echo "--- Creating symbolic link to job directory :file_folder:" && \
      sleep 5 && ln -s "$(pwd)" /data/job && cd /data/job && \
      echo "+++ Building :hammer:" && \
      echo 1 | ./eosio_build.sh && \
      echo "--- Compressing build directory :compression:" && \
      tar -pczf build.tar.gz build/
    label: ":darwin: Mojave Build"
    agents:
      - "role=builder"
      - "os=mojave"
    artifact_paths: "build.tar.gz"
    timeout: 60

  - wait

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: High Sierra Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        ln -s "$(pwd)" /data/job && cd /data/job/build && ctest -j8 -LE _tests --output-on-failure
    label: ":darwin: High Sierra Tests"
    agents:
      - "role=macos-builder"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: High Sierra Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        ln -s "$(pwd)" /data/job && cd /data/job/build && ctest -L nonparallelizable_tests --output-on-failure
    label: ":darwin: High Sierra NP Tests"
    agents:
      - "role=macos-builder"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: Mojave Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        ln -s "$(pwd)" /data/job && cd /data/job/build && ctest -j8 -LE _tests --output-on-failure
    label: ":darwin: Mojave Tests"
    agents:
      - "role=builder"
      - "os=mojave"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: Mojave Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        ln -s "$(pwd)" /data/job && cd /data/job/build && ctest -L nonparallelizable_tests --output-on-failure
    label: ":darwin: Mojave NP Tests"
    agents:
      - "role=builder"
      - "os=mojave"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    timeout: 60
    
  - wait

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: High Sierra Build" && \
        tar -zxf build.tar.gz && \
        echo "+++ :microscope: Starting package build" && \
        ln -s "$(pwd)" /data/job && cd /data/job/build/packages && bash generate_package.sh brew
    label: ":darwin: High Sierra Package Builder"
    agents:
      - "role=macos-builder"
      - "os=high-sierra"
    artifact_paths:
      - "build/packages/*.tar.gz"
      - "build/packages/*.rb"
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: Mojave Build" && \
        tar -zxf build.tar.gz && \
        echo "+++ :microscope: Starting package build" && \
        ln -s "$(pwd)" /data/job && cd /data/job/build/packages && bash generate_package.sh brew
    label: ":darwin: Mojave Package Builder"
    agents:
      - "role=builder"
      - "os=mojave"
    artifact_paths:
      - "build/packages/*.tar.gz"
      - "build/packages/*.rb"
    timeout: 60
